fix: fix the docker image detection logic
GoogleCloudPlatform/docker-ci-helper pull request #35
Opened 2020-09-15 22:53 UTC by tmatsuo

2020-09-15 23:15 UTC, chingor13 requested changes
Can you create and link an issue describing what case this fixes?

2020-09-15 23:15 UTC, chingor13 commented on CHANGELOG.md
> +  fix the docker image detection logic [#34](https://github.com/GoogleCloudPlatform/docker-ci-helper/pull/34)
```suggestion
  fix the docker image detection logic [#35](https://github.com/GoogleCloudPlatform/docker-ci-helper/pull/35)
```

2020-09-16 03:37 UTC, tmatsuo commented
@chingor13 Thanks, done

2020-09-16 14:50 UTC, chingor13 approved these changes

2020-09-16 16:38 UTC, merged